source 'https://rubygems.org'

# Cliente Binance
gem 'binance', '~> 1.3'

# ZeroMQ
gem 'ffi-rzmq', '~> 2.0'

# Utilitários
gem 'json', '~> 2.6'
gem 'logger', '~> 1.5'
gem 'dotenv', '~> 2.8'

# Desenvolvimento
group :development do
  gem 'rspec', '~> 3.12'
  gem 'rubocop', '~> 1.50'
  gem 'pry', '~> 0.14'
end 